### ISSUE TITLE
"Corrupted dir pair at {0x0, 0x1}" with version 1.61

### ISSUE THREAD

**Issue by shawnshekari** [tjko/fanpico#80]
Thanks for such an awesome product.  I bought my kit (0804D) back at the end of Jan and just got it soldered up today. 

Of course, I went right for the latest firmware and ran into an issue.  The previous couple version (1.60 & 1.50) didn't have any issues.  

But I noticed another serial message that made me think that perhaps the older version had corrected the directory issue and sure enough now the 1.61 version also runs without an error.  The two messages in Putty below.  The first was by flashing 1.61 (and I did that a couple times with the same results.) And the second was when I tried 1.5.  After that the three versions I have tried all worked.

![image](https://github.com/tjko/fanpico/assets/602278/a3ac35a4-9ebb-4acc-810e-a48673788cf9)

I haven't tried any fan control yet but so far I am so impressed with the project.
![20240302_191258](https://github.com/tjko/fanpico/assets/602278/5c0af63d-022a-43fb-a943-658382a8febc)

**Comment by tjko** [comment]
Interesting, so did I understand correctly that this happened when installing v1.6.1 firmware on a "blank" Pico?  And after 'downgrading' to earlier firmware that seemed to fix the issue? 

Probably something to do with v1.6.1 using newer version of LittleFS library... I'll see if I can replicate the issue you saw...

**Comment by tjko** [comment]
Thanks for pointing this out. It was indeed a bug that was introduced when switching to use latest LittleFS version in fanpico.

Fix is now checked in 65f9d447e4fc8ecb60d4e0e5a42c76343d032586

**Comment by tjko** [comment]
New firmware release v1.6.2 now contains this fix: https://github.com/tjko/fanpico/releases/tag/v1.6.2
